function showFeedbackWindowColor(win,...
                                 respError,...
                                 reportedColor,...
                                 targetColor,...
                                 targetOrientation,...
                                 probeTriangleHeight,...
                                 probeTriangleWidth)

Screen('FillRect', win, [128 128 128]);

[screenXpixels, screenYpixels] = Screen('WindowSize', win);

xCenter = screenXpixels/2;
yCenter = screenYpixels/2;

white = [255 255 255];

Screen('TextSize',win,28);

DrawFormattedText(win,...
    sprintf('Color Error: %.0f°',abs(respError)),...
    'center',70,white);


actualX   = xCenter - 200;
reportedX = xCenter + 200;
triangleY = yCenter + 50;

DrawFormattedText(win,...
    'Actual',...
    actualX-40,...
    triangleY-170,...
    white);

DrawFormattedText(win,...
    'Reported',...
    reportedX-55,...
    triangleY-170,...
    white);

feedbackHeight = probeTriangleHeight * 1.5;
feedbackWidth  = probeTriangleWidth * 1.5;

actualTriangle = Triangle(...
    targetOrientation,...
    actualX,...
    triangleY,...
    feedbackHeight,...
    feedbackWidth);

reportedTriangle = Triangle(...
    targetOrientation,...
    reportedX,...
    triangleY,...
    feedbackHeight,...
    feedbackWidth);

Screen('FillPoly',win,...
       targetColor,...
       actualTriangle.setTriangleVertices());

Screen('FillPoly',win,...
       reportedColor,...
       reportedTriangle.setTriangleVertices());

Screen('Flip',win);

end