function showFeedbackWindow(win,scoreEarned,totalScore,...
    reportedTheta,actualTheta,...
    xCenter,yCenter,...
    triangHeight,triangWidth)

% Coding Challenge Question 3:
% Display feedback at the end of each trial, including points earned,
% total points earned, and an overlay of the reported and actual
% triangle orientations.

% Actual orientation (white)
actualTriangle = Triangle(actualTheta,...
    xCenter,yCenter,...
    triangHeight,triangWidth);

% Reported orientation (black)
reportedTriangle = Triangle(reportedTheta,...
    xCenter,yCenter,...
    triangHeight,triangWidth);

% Draw actual triangle
Screen('FillPoly',win,[255 255 255],...
    actualTriangle.setTriangleVertices());

% Draw reported triangle on top
Screen('FillPoly',win,[0 0 0],...
    reportedTriangle.setTriangleVertices());

% Display scores
feedbackText = sprintf(['Points earned this trial: %.2f\n' ...
                        'Total points earned: %.2f'],...
                        scoreEarned,totalScore);

DrawFormattedText(win,...
    feedbackText,...
    'center',50,...
    [255 255 255]);

Screen('Flip',win);

end